name: my_book_library
description: "A new Flutter project."
publish_to: 'none'
version: 0.5.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  supabase_codegen_flutter: ^3.0.1
  supabase_flutter: ^2.10.3
  supabase_auth_ui: ^0.5.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logging: ^1.2.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7
  shared_preferences: ^2.2.2 
  package_info_plus: ^5.0.1
  mobile_scanner: ^5.2.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  
dependency_overrides:
  # If you have conflicts, add this
  web: ^0.5.1

flutter:
  assets:
    - .env
  uses-material-design: true

supabase_codegen:
  env: .env # Overrides default: .env
  output: lib/models/supabase # Overrides default: supabase/types
  tag: v1 # Overrides default: ''
  debug: true # Overrides default: false
  skipFooter: true # Overrides default: false